schema = 3

[mod]
  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.2.4'
    hash = 'sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.11'
    hash = 'sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE='
