package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			for _, svc := range f.Services {
				generateService(gen, f, svc)
			}
		}
		return nil
	})
}

func generateService(gen *protogen.Plugin, file *protogen.File, svc *protogen.Service) {
	filename := file.GeneratedFilenamePrefix + "_greetdeez.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-greetdeez-go. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// Imports
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"fmt"`)
	g.P()
	g.P(`	"github.com/nickheyer/greetdeez/pkg/rpc"`)
	g.P(")")
	g.P()

	ifaceName := svc.GoName + "Server"
	unimplName := "Unimplemented" + ifaceName

	// Server interface
	g.P("// ", ifaceName, " is the server API for ", svc.GoName, ".")
	g.P("type ", ifaceName, " interface {")
	for _, m := range svc.Methods {
		g.P("	", m.GoName, "(context.Context, *", m.Input.GoIdent.GoName, ") (*", m.Output.GoIdent.GoName, ", error)")
	}
	g.P("}")
	g.P()

	// Unimplemented struct
	g.P("// ", unimplName, " can be embedded for forward compatibility.")
	g.P("type ", unimplName, " struct{}")
	g.P()
	for _, m := range svc.Methods {
		g.P("func (", unimplName, ") ", m.GoName, "(context.Context, *", m.Input.GoIdent.GoName, ") (*", m.Output.GoIdent.GoName, ", error) {")
		g.P(`	return nil, fmt.Errorf("greetdeez: `, m.GoName, ` not implemented")`)
		g.P("}")
	}
	g.P()

	// Registration function
	fullSvcName := fmt.Sprintf("%s.%s", strings.TrimPrefix(string(file.Desc.Package()), ""), svc.Desc.Name())
	g.P("// Register", ifaceName, " registers all handlers with the dispatcher.")
	g.P("func Register", ifaceName, "(d *rpc.Dispatcher, srv ", ifaceName, ") {")
	for _, m := range svc.Methods {
		method := fmt.Sprintf("%s/%s", fullSvcName, m.Desc.Name())
		g.P("	rpc.Handle(d, \"", method, "\",")
		g.P("		func(ctx context.Context, req *", m.Input.GoIdent.GoName, ") (*", m.Output.GoIdent.GoName, ", error) {")
		g.P("			return srv.", m.GoName, "(ctx, req)")
		g.P("		})")
	}
	g.P("}")
}
