package main

import (
	"fmt"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			for _, svc := range f.Services {
				generateTypes(gen, f)
				generateClient(gen, f, svc)
			}
		}
		return nil
	})
}

// ── types.ts ────────────────────────────────────────────────────

func generateTypes(gen *protogen.Plugin, file *protogen.File) {
	g := gen.NewGeneratedFile("types.ts", "")
	g.P("// Code generated by protoc-gen-greetdeez-es. DO NOT EDIT.")
	g.P()

	// Enums
	g.P("// ── Enums ───────────────────────────────────────────────────────")
	g.P()
	for _, e := range file.Enums {
		g.P("export enum ", stripPrefix(string(e.Desc.Name())), " {")
		prefix := commonEnumPrefix(e)
		for _, v := range e.Values {
			name := strings.TrimPrefix(string(v.Desc.Name()), prefix)
			g.P("  ", name, " = ", v.Desc.Number(), ",")
		}
		g.P("}")
		g.P()
	}

	// Messages
	g.P("// ── Messages ────────────────────────────────────────────────────")
	g.P()
	for _, m := range file.Messages {
		g.P("export interface ", m.GoIdent.GoName, " {")
		for _, f := range m.Fields {
			tsName := toCamelCase(string(f.Desc.Name()))
			tsType := protoToTSType(f)
			optional := isOptionalField(f)
			if optional {
				g.P("  ", tsName, "?: ", tsType, ";")
			} else {
				g.P("  ", tsName, ": ", tsType, ";")
			}
		}
		g.P("}")
		g.P()
	}
}

// ── client.ts ───────────────────────────────────────────────────

func generateClient(gen *protogen.Plugin, file *protogen.File, svc *protogen.Service) {
	g := gen.NewGeneratedFile("client.ts", "")
	g.P("// Code generated by protoc-gen-greetdeez-es. DO NOT EDIT.")
	g.P()

	// Import types
	g.P("import type {")
	for _, m := range svc.Methods {
		g.P("  ", m.Input.GoIdent.GoName, ", ", m.Output.GoIdent.GoName, ",")
	}
	g.P(`} from "./types.js";`)
	g.P()

	// Client interface
	g.P("// ── Client interface ────────────────────────────────────────────")
	g.P()
	g.P("export interface ", svc.GoName, "Client {")
	for _, m := range svc.Methods {
		methodName := lowerFirst(m.GoName)
		hasRequiredFields := messageHasRequiredFields(m.Input)
		if hasRequiredFields {
			g.P("  ", methodName, "(req: ", m.Input.GoIdent.GoName, "): Promise<", m.Output.GoIdent.GoName, ">;")
		} else {
			g.P("  ", methodName, "(req?: ", m.Input.GoIdent.GoName, "): Promise<", m.Output.GoIdent.GoName, ">;")
		}
	}
	g.P("}")
	g.P()

	// Mock type
	g.P("// ── Dev mock ────────────────────────────────────────────────────")
	g.P()
	g.P("export type ", svc.GoName, "Mock = Partial<", svc.GoName, "Client>;")
	g.P()

	// Defaults
	g.P("// Default empty responses (generated, one per method).")
	g.P("const defaults: { [K in keyof ", svc.GoName, "Client]: () => ReturnType<", svc.GoName, "Client[K]> } = {")
	for _, m := range svc.Methods {
		methodName := lowerFirst(m.GoName)
		defaultVal := generateDefaultResponse(m.Output)
		g.P("  ", methodName, ":        async () => (", defaultVal, "),")
	}
	g.P("};")
	g.P()

	// Internal protobuf imports
	// protoc-gen-es outputs to {proto_path}/ relative to the out dir
	greeterPrefix := "./" + strings.ReplaceAll(string(file.Desc.Package()), ".", "/")
	transportPrefix := "./transport/v1"

	g.P("// ── Internal: protobuf serialization (not re-exported) ──────────")
	g.P()
	g.P(`import { toBinary, fromBinary, create } from "@bufbuild/protobuf";`)
	g.P(`import { RpcEnvelopeSchema, RpcResultSchema } from "`, transportPrefix, `/transport_pb.js";`)

	// Collect all unique schema imports from greeter_pb
	g.P("import {")
	for _, m := range svc.Methods {
		g.P("  ", m.Input.GoIdent.GoName, "Schema, ", m.Output.GoIdent.GoName, "Schema,")
	}
	g.P(`} from "`, greeterPrefix, `/greeter_pb.js";`)
	g.P()

	// WebViewRpc type
	g.P("type WebViewRpc = (payload: string) => Promise<string>;")
	g.P()

	// wireCall function
	g.P("function wireCall(")
	g.P("  transport: WebViewRpc,")
	g.P("  method: string,")
	g.P("  reqSchema: any,")
	g.P("  respSchema: any,")
	g.P("): (req?: any) => Promise<any> {")
	g.P("  return async (req: any = {}) => {")
	g.P("    const payload = toBinary(reqSchema, create(reqSchema, req));")
	g.P("    const envelope = create(RpcEnvelopeSchema, { method, payload });")
	g.P("    const b64 = btoa(String.fromCharCode(...toBinary(RpcEnvelopeSchema, envelope)));")
	g.P()
	g.P("    const resultB64 = await transport(b64);")
	g.P("    const resultBytes = Uint8Array.from(atob(resultB64), c => c.charCodeAt(0));")
	g.P("    const result = fromBinary(RpcResultSchema, resultBytes);")
	g.P()
	g.P("    if (result.error) {")
	g.P("      throw new Error(result.error);")
	g.P("    }")
	g.P("    return fromBinary(respSchema, result.payload);")
	g.P("  };")
	g.P("}")
	g.P()

	// Methods map
	fullSvcName := fmt.Sprintf("%s.%s", file.Desc.Package(), svc.Desc.Name())
	g.P("const methods = {")
	for _, m := range svc.Methods {
		methodName := lowerFirst(m.GoName)
		fullMethodName := fmt.Sprintf("%s/%s", fullSvcName, m.Desc.Name())
		g.P("  ", methodName, ": [\"", fullMethodName, "\", ", m.Input.GoIdent.GoName, "Schema, ", m.Output.GoIdent.GoName, "Schema],")
	}
	g.P("} as const;")
	g.P()

	// Global type declaration
	g.P("// ── Public API ──────────────────────────────────────────────────")
	g.P()
	g.P("declare global {")
	g.P("  interface Window {")
	g.P("    __greetdeez_rpc__?: WebViewRpc;")
	g.P("  }")
	g.P("}")
	g.P()

	// CreateClientOptions
	g.P("export interface CreateClientOptions {")
	g.P("  dev?: ", svc.GoName, "Mock;")
	g.P("}")
	g.P()

	// createClient function
	g.P("export function create", svc.GoName, "Client(opts?: CreateClientOptions): ", svc.GoName, "Client {")
	g.P("  const transport = typeof window !== \"undefined\" ? window.__greetdeez_rpc__ : undefined;")
	g.P()
	g.P("  if (transport) {")
	g.P("    const client = {} as ", svc.GoName, "Client;")
	g.P("    for (const [name, [method, reqSchema, respSchema]] of Object.entries(methods)) {")
	g.P("      (client as any)[name] = wireCall(transport, method, reqSchema, respSchema);")
	g.P("    }")
	g.P("    return client;")
	g.P("  }")
	g.P()
	g.P("  const mock = opts?.dev ?? {};")
	g.P("  const client = {} as ", svc.GoName, "Client;")
	g.P("  for (const name of Object.keys(defaults) as (keyof ", svc.GoName, "Client)[]) {")
	g.P("    (client as any)[name] = (mock as any)[name] ?? defaults[name];")
	g.P("  }")
	g.P("  return client;")
	g.P("}")
}

// ── Helpers ─────────────────────────────────────────────────────

func stripPrefix(name string) string {
	return name
}

func commonEnumPrefix(e *protogen.Enum) string {
	if len(e.Values) == 0 {
		return ""
	}
	// Find common prefix of all enum value names
	first := string(e.Values[0].Desc.Name())
	prefix := first
	for _, v := range e.Values[1:] {
		name := string(v.Desc.Name())
		for !strings.HasPrefix(name, prefix) {
			prefix = prefix[:len(prefix)-1]
		}
	}
	return prefix
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func lowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func protoToTSType(f *protogen.Field) string {
	if f.Desc.IsList() {
		return protoScalarToTS(f) + "[]"
	}
	return protoScalarToTS(f)
}

func protoScalarToTS(f *protogen.Field) string {
	switch f.Desc.Kind() {
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.Int32Kind, protoreflect.Int64Kind,
		protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.Sint32Kind, protoreflect.Sint64Kind,
		protoreflect.Fixed32Kind, protoreflect.Fixed64Kind,
		protoreflect.Sfixed32Kind, protoreflect.Sfixed64Kind,
		protoreflect.FloatKind, protoreflect.DoubleKind:
		return "number"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "Uint8Array"
	case protoreflect.EnumKind:
		return stripPrefix(string(f.Desc.Enum().Name()))
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return f.Message.GoIdent.GoName
	default:
		return "unknown"
	}
}

func isOptionalField(f *protogen.Field) bool {
	return f.Desc.HasOptionalKeyword()
}

func messageHasRequiredFields(m *protogen.Message) bool {
	for _, f := range m.Fields {
		if !isOptionalField(f) {
			return true
		}
	}
	return false
}

func generateDefaultResponse(m *protogen.Message) string {
	if len(m.Fields) == 0 {
		return "{}"
	}

	parts := []string{}
	for _, f := range m.Fields {
		name := toCamelCase(string(f.Desc.Name()))
		val := defaultFieldValue(f)
		parts = append(parts, fmt.Sprintf("%s: %s", name, val))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func defaultFieldValue(f *protogen.Field) string {
	if f.Desc.IsList() {
		return "[]"
	}
	switch f.Desc.Kind() {
	case protoreflect.BoolKind:
		return "false"
	case protoreflect.Int32Kind, protoreflect.Int64Kind,
		protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.Sint32Kind, protoreflect.Sint64Kind,
		protoreflect.Fixed32Kind, protoreflect.Fixed64Kind,
		protoreflect.Sfixed32Kind, protoreflect.Sfixed64Kind,
		protoreflect.FloatKind, protoreflect.DoubleKind:
		return "0"
	case protoreflect.StringKind:
		return `""`
	case protoreflect.BytesKind:
		return "new Uint8Array()"
	case protoreflect.EnumKind:
		return "0"
	case protoreflect.MessageKind:
		return generateDefaultMessage(f.Message)
	default:
		return "undefined"
	}
}

func generateDefaultMessage(m *protogen.Message) string {
	if len(m.Fields) == 0 {
		return "{}"
	}
	parts := []string{}
	for _, f := range m.Fields {
		name := toCamelCase(string(f.Desc.Name()))
		val := defaultFieldValue(f)
		parts = append(parts, fmt.Sprintf("%s: %s", name, val))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}
